### ISSUE TITLE
A controllabe outlet

### ISSUE THREAD

**Issue by przemech** [knonyks/onyks-iot-monitor-power#1]
If the project will be built into a power strip, then I thought why not to control the outlets?
But I think we don't need to control them all, but maybe just one?

This is just an idea, not to be done yet. Perhaps this is already over-engineering?

**Comment by macmysz** [comment]
It's no problem at all to add relay controling outlets. For more than one relay i could add connetors with power and signal. They could be used for anything else. I have quite a lot free pins at the moment.

**Comment by macmysz** [comment]
I added relay and extra free gpio. If you have any suggestions to change J16 symbol.

**Comment by przemech** [comment]
I think you could use just a connector like e.g.:
`Conn_01x07
Generic connector, single row, 01x07, script generated (kicad-library-utils/schlib/autogen/connector/)`

**Comment by macmysz** [comment]
I will change it. I still think how to place components to make pcb smaller. To next Monday i will try to finish it.

**Comment by macmysz** [comment]
i added relay and changed connector to 01x08
